### ISSUE TITLE
Any way to specify which Unicode character to use?

### ISSUE THREAD

**Issue by benedfit** [twolfson/grunt-fontsmith#6]

**Comment by sevenfoxes** [comment]
I'm looking for this too. Primarily because the character would be able to be "synced" to an indesign file. I'm going to attempt to make the change but looking at it, it might be a bit too far beyond my abilities.

**Comment by twolfson** [comment]
This project is out of date with the latest icomoon website (i.e. it's pointing to `/app-old` instead of `/app`). I would prefer to move to the new site before adding more features to the existing engine. I will take a look this weekend to see how much work that is.

If you submit a PR for the new feature before the move happens, I will probably still accept it.

**Comment by sevenfoxes** [comment]
I'll let you see what's up this weekend and then I'll try and help from there. I wasn't even aware there was an old app (I haven't got to dig as hard as I want yet).

**Comment by twolfson** [comment]
I am going to flip flop back on this. It looks like it would be an entire rewrite of the engine (previous app was HTTP based, new one is in-browser/angular). PhantomJS scripts tend to be more finnicky since it is a separate execution context.

I am hesitant to deprecate the project due to lack of personal usage/maintenance but haven't yet.

During my research, I found `icomoon-build` which seems more active and is using the new app. Maybe they can add in ligature support for you?

https://www.npmjs.com/package/icomoon-build

**Comment by benedfit** [comment]
Closing as I've moved to an SVG workflow

**Comment by twolfson** [comment]
Going to leave this open as it is still a good feature to add.
